# Do not exfiltrate, just inform that you would have
dryRun: true
# AWS Region
region: eu-west-1
# Prefix of your Auto Scaling Group
asgPrefix: dev1-av-ui
# 2 failing checks will trigger an exfiltration
threshold: 2
# Check interval
interval: 4000
# Webapp port
port: 8080
# Guess what...
checkUrl: /check/app
